// AUTH MIDDLEWARES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const FETCH_USER = 'FETCH_USER';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const SET_PIN = 'auth/setPin';

// BUDA MIDDLEWARE
export const BUDA_AUTH_REQUEST = 'BUDA_AUTH_REQUEST';
export const BUDA_GET_BALANCE = 'BUDA_GET_BALANCE';
export const BUDA_CLEAN_ERROR = 'buda/cleanError';

// PAYMENT MIDDLEWARE

export const BUDA_PAYMENT = 'BUDA_PAYMENT';
export const BUDA_QUOTATION = 'BUDA_QUOTATION';
export const BUDA_GET_PAYMENT_HISTORY = 'BUDA_GET_PAYMENT_HISTORY';
export const BUDA_UNMOUNT_LAST_PAYMENT = 'BUDA_UNMOUNT_LAST_PAYMENT';
export const BITSPLIT_WITHDRAWAL = 'BITSPLIT_WITHDRAWAL';
export const BITSPLIT_DEPOSIT = 'BITSPLIT_DEPOSIT';

// FIREBASE MIDDLEWARE

export const FIREBASE_NOTIFICATIONS = 'FIREBASE_NOTIFICATIONS';

export const START_SETUP = 'onstart/finishStart';

// SPLITWISE MIDDLEWARE

export const SPLITWISE_GET_DEBTS = 'SPLITWISE_GET_DEBTS';

// TRANSACTIONS MIDDLEWARE

export const GET_WALLETS_BALANCES = 'GET_WALLETS_BALANCES';
