
// AUTH MIDDLEWARES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// BUDA MIDDLEWARE
export const BUDA_AUTH_REQUEST = 'BUDA_AUTH_REQUEST';
export const BUDA_GET_BALANCE = 'BUDA_GET_BALANCE';

// PAYMENT MIDDLEWARE

export const BUDA_PAYMENT = 'BUDA_PAYMENT';
export const BUDA_QUOTATION = 'BUDA_QUOTATION';
export const BUDA_UNMOUNT_LAST_PAYMENT = 'BUDA_UNMOUNT_LAST_PAYMENT';
